### ISSUE TITLE
Wrong version console Error

### ISSUE THREAD

**Issue by dkbutxlo** [RemoteLight/OpenRGB-Plugin#2]
Plugin doesnt work with the current version of Remotelight 0.24

[22:54:33] [ERROR] PluginManager.run(): Failed to load plugin: openrgb-plugin-1.3.2.jar: de.lars.remotelightplugins.exceptions.PluginLoadException: The plugin does require at least RemoteLight version 'v0.2.5-beta'. Current version: v0.2.4
	at de.lars.remotelightplugins.PluginManager.checkPluginRequirements(PluginManager.java:522)
	at de.lars.remotelightplugins.PluginManager.access$200(PluginManager.java:57)
	at de.lars.remotelightplugins.PluginManager$1.run(PluginManager.java:132)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dkbutxlo** [comment]
Edit: 

Tutorial still says 0.24, current release needs the 0.25beta
